// KEY INSIGHTS COMPONENT
// Displays natural language insights about the forecast
// /Users/matthewsimon/Projects/acdc-digital/soloist/renderer/app/dashboard/soloist/_components/KeyInsights.tsx

"use client";

import React from "react";
import { Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";
import { useWeekData, useSelectedDay } from "@/store/soloistStore";

interface KeyInsightsProps {
  className?: string;
}

export function KeyInsights({ className }: KeyInsightsProps) {
  const weekData = useWeekData();
  const selectedDay = useSelectedDay();

  // Generate conversational insights based on the week data
  // In a real implementation, these would come from AI analysis
  const conversationalInsight = React.useMemo(() => {
    // Placeholder conversational insight - this would be generated by AI based on actual data
    return "Your energy peaks midweek—especially Wednesdays—and rides into the weekend. Thursdays are consistently tougher, though. Maybe it's time to schedule some self-care there.\n\nI also notice your evenings are brighter than mornings, and when you have a rough day, you bounce back fast. That resilience is worth celebrating.";
  }, [weekData]);

  return (
    <div className={cn("flex flex-col flex-1 min-h-0", className)}>
      {/* Header */}
      <div className="flex items-center gap-2 px-4 py-3 flex-shrink-0">
        <h3 className="text-sm font-medium text-neutral-900 dark:text-neutral-100">
          Key Insights
        </h3>
      </div>

      {/* Conversational Insight */}
      <div className="flex-1 px-4 pb-4 overflow-y-auto min-h-0">
        <div className="text-xs lg:text-sm text-neutral-700 dark:text-neutral-300 leading-relaxed space-y-3">
          {conversationalInsight.split('\n\n').map((paragraph, index) => (
            <p key={index}>{paragraph}</p>
          ))}
        </div>
      </div>
    </div>
  );
}

export default KeyInsights;
