graph LR
    app__components_activity__components_agents_AgentsPanel_tsx[AgentsPanel.tsx]
    app__components_activity__components_agents_index_ts[index.ts]
    app__components_activity__components_calendar_CalendarPanel_tsx[CalendarPanel.tsx]
    app__components_activity__components_calendar_CalendarTab_tsx[CalendarTab.tsx]
    app__components_activity__components_calendar_index_ts[index.ts]
    app__components_activity__components_connections_DashSocialConnections_tsx[DashSocialConnections.tsx]
    app__components_activity__components_connections_SocialConnectors_tsx[SocialConnectors.tsx]
    app__components_activity__components_connections_index_ts[index.ts]
    app__components_activity__components_connections_resources_useSocialConnectionSync_ts[useSocialConnectionSync.ts]
    app__components_activity__components_connections_useSocialConnectionSync_ts[useSocialConnectionSync.ts]
    app__components_activity__components_extensions_ExtensionsPanel_tsx[ExtensionsPanel.tsx]
    app__components_activity__components_extensions_index_ts[index.ts]
    app__components_activity__components_fileExplorer_FileContextMenu_tsx[FileContextMenu.tsx]
    app__components_activity__components_fileExplorer_FileExplorerPanel_tsx[FileExplorerPanel.tsx]
    app__components_activity__components_fileExplorer_FileExplorerTab_tsx[FileExplorerTab.tsx]
    app__components_activity__components_fileExplorer_FileTreeItem_tsx[FileTreeItem.tsx]
    app__components_activity__components_fileExplorer_index_ts[index.ts]
    app__components_activity__components_index_ts[index.ts]
    app__components_activity__components_userProfle_UserProfile_tsx[UserProfile.tsx]
    app__components_activity__components_userProfle_userConsole_tsx[userConsole.tsx]