-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkZHCpWookL+mSZ1w
4IgmIuCyIqJS2joZdy5dRYaBRvGgCgYIKoZIzj0DAQehRANCAATja6R1aHhuhAxQ
tkvPqc5p9X0PVLKjvdySZX3CXudqrEXg2Zlc/xMWP8SaTnWXkEvMj2nb4OG/SBL0
yqe0tcu8
-----END PRIVATE KEY-----