// NASDAQ-100 COMPANY DATA
// /Users/matthewsimon/Projects/acdc-digital/smnb/smnb/lib/services/livefeed/nasdaq100.ts

export const NASDAQ_100_COMPANIES = {
  // Top tech companies with their tickers and common mentions
  'AAPL': { name: 'Apple', aliases: ['Apple', 'iPhone', 'iPad', 'Mac', 'iOS', 'MacBook', 'AirPods'] },
  'MSFT': { name: 'Microsoft', aliases: ['Microsoft', 'Windows', 'Azure', 'Office', 'Xbox', 'GitHub', 'Copilot'] },
  'GOOGL': { name: 'Alphabet Class A', aliases: ['Google', 'Alphabet', 'YouTube', 'Android', 'Chrome', 'Gemini', 'Bard'] },
  'GOOG': { name: 'Alphabet Class C', aliases: ['Google', 'Alphabet', 'YouTube', 'Android', 'Chrome', 'Gemini', 'Bard'] },
  'AMZN': { name: 'Amazon', aliases: ['Amazon', 'AWS', 'Prime', 'Alexa', 'Twitch', 'Whole Foods'] },
  'NVDA': { name: 'NVIDIA', aliases: ['NVIDIA', 'Nvidia', 'GeForce', 'CUDA', 'RTX', 'H100', 'A100'] },
  'META': { name: 'Meta', aliases: ['Meta', 'Facebook', 'Instagram', 'WhatsApp', 'Oculus', 'Quest', 'Threads'] },
  'TSLA': { name: 'Tesla', aliases: ['Tesla', 'Elon Musk', 'Model S', 'Model 3', 'Model X', 'Model Y', 'Cybertruck', 'FSD'] },
  'AVGO': { name: 'Broadcom', aliases: ['Broadcom', 'VMware', 'Symantec'] },
  'COST': { name: 'Costco', aliases: ['Costco', 'Kirkland'] },
  'LIN': { name: 'Linde', aliases: ['Linde', 'Praxair'] },
  'ADBE': { name: 'Adobe', aliases: ['Adobe', 'Photoshop', 'Illustrator', 'Acrobat', 'Creative Cloud', 'PDF'] },
  'CSCO': { name: 'Cisco', aliases: ['Cisco', 'WebEx', 'Meraki'] },
  'AMD': { name: 'AMD', aliases: ['AMD', 'Ryzen', 'Radeon', 'EPYC', 'Threadripper'] },
  'NFLX': { name: 'Netflix', aliases: ['Netflix'] },
  'INTC': { name: 'Intel', aliases: ['Intel', 'Core i7', 'Core i9', 'Xeon'] },
  'MU': { name: 'Micron', aliases: ['Micron Technology', 'Micron', 'Crucial'] },
  'MSTR': { name: 'MicroStrategy', aliases: ['MicroStrategy'] },
  'QCOM': { name: 'Qualcomm', aliases: ['Qualcomm', 'Snapdragon'] },
  'TMUS': { name: 'T-Mobile', aliases: ['T-Mobile', 'Sprint'] },
  'CMCSA': { name: 'Comcast', aliases: ['Comcast', 'Xfinity', 'NBCUniversal'] },
  'HON': { name: 'Honeywell', aliases: ['Honeywell International', 'Honeywell'] },
  'PEP': { name: 'PepsiCo', aliases: ['Pepsi', 'PepsiCo', "Lay's", 'Doritos', 'Gatorade', 'Quaker'] },
  'AMGN': { name: 'Amgen', aliases: ['Amgen'] },
  'AMAT': { name: 'Applied Materials', aliases: ['Applied Materials', 'AMAT'] },
  'TXN': { name: 'Texas Instruments', aliases: ['Texas Instruments', 'TI'] },
  'INTU': { name: 'Intuit', aliases: ['Intuit', 'QuickBooks', 'TurboTax', 'Mint', 'Credit Karma'] },
  'ISRG': { name: 'Intuitive Surgical', aliases: ['Intuitive Surgical', 'da Vinci'] },
  'BKNG': { name: 'Booking', aliases: ['Booking', 'Booking.com', 'Priceline', 'Kayak', 'OpenTable'] },
  'SBUX': { name: 'Starbucks', aliases: ['Starbucks'] },
  'GILD': { name: 'Gilead Sciences', aliases: ['Gilead'] },
  'MDLZ': { name: 'Mondelez', aliases: ['Mondelez', 'Oreo', 'Cadbury', 'Toblerone'] },
  'ADI': { name: 'Analog Devices', aliases: ['Analog Devices', 'ADI'] },
  'VRTX': { name: 'Vertex', aliases: ['Vertex Pharmaceuticals'] },
  'REGN': { name: 'Regeneron', aliases: ['Regeneron'] },
  'PANW': { name: 'Palo Alto Networks', aliases: ['Palo Alto Networks', 'PAN'] },
  'LRCX': { name: 'Lam Research', aliases: ['Lam Research'] },
  'SNPS': { name: 'Synopsys', aliases: ['Synopsys'] },
  'CDNS': { name: 'Cadence', aliases: ['Cadence Design'] },
  'MELI': { name: 'MercadoLibre', aliases: ['MercadoLibre', 'Mercado Libre'] },
  'KLAC': { name: 'KLA', aliases: ['KLA', 'KLA-Tencor'] },
  'ASML': { name: 'ASML', aliases: ['ASML'] },
  'CRWD': { name: 'CrowdStrike', aliases: ['CrowdStrike', 'Falcon'] },
  'AXON': { name: 'Axon Enterprise', aliases: ['Axon', 'Taser'] },
  'MRVL': { name: 'Marvell', aliases: ['Marvell Technology'] },
  'FTNT': { name: 'Fortinet', aliases: ['Fortinet', 'FortiGate'] },
  'ADSK': { name: 'Autodesk', aliases: ['Autodesk', 'AutoCAD', 'Revit', 'Maya', '3ds Max'] },
  'WDAY': { name: 'Workday', aliases: ['Workday'] },
  'NXPI': { name: 'NXP', aliases: ['NXP Semiconductors'] },
  'ORLY': { name: "O'Reilly Automotive", aliases: ["O'Reilly", "O'Reilly Auto Parts"] },
  'CTAS': { name: 'Cintas', aliases: ['Cintas'] },
  'CSX': { name: 'CSX', aliases: ['CSX Corporation', 'CSX Transportation'] },
  'MAR': { name: 'Marriott', aliases: ['Marriott International', 'Marriott'] },
  'PCAR': { name: 'PACCAR', aliases: ['PACCAR', 'Peterbilt', 'Kenworth'] },
  'CHTR': { name: 'Charter Communications', aliases: ['Charter', 'Spectrum'] },
  'AEP': { name: 'American Electric Power', aliases: ['AEP', 'American Electric'] },
  'LULU': { name: 'Lululemon', aliases: ['Lululemon', 'lulu'] },
  'ROP': { name: 'Roper Technologies', aliases: ['Roper'] },
  'ABNB': { name: 'Airbnb', aliases: ['Airbnb'] },
  'PYPL': { name: 'PayPal', aliases: ['PayPal', 'Venmo', 'Braintree'] },
  'PLTR': { name: 'Palantir', aliases: ['Palantir Technologies', 'Palantir'] },
  'APP': { name: 'AppLovin', aliases: ['AppLovin'] },
  'SHOP': { name: 'Shopify', aliases: ['Shopify'] },
  'MNST': { name: 'Monster Beverage', aliases: ['Monster Energy', 'Monster'] },
  'ROST': { name: 'Ross Stores', aliases: ['Ross', 'Ross Stores'] },
  'CPRT': { name: 'Copart', aliases: ['Copart'] },
  'MCHP': { name: 'Microchip', aliases: ['Microchip Technology'] },
  'DXCM': { name: 'Dexcom', aliases: ['Dexcom'] },
  'PAYX': { name: 'Paychex', aliases: ['Paychex'] },
  'ODFL': { name: 'Old Dominion', aliases: ['Old Dominion Freight'] },
  'TEAM': { name: 'Atlassian', aliases: ['Atlassian', 'Jira', 'Confluence', 'Bitbucket', 'Trello'] },
  'TTD': { name: 'Trade Desk', aliases: ['The Trade Desk', 'Trade Desk'] },
  'GEHC': { name: 'GE HealthCare', aliases: ['GE HealthCare', 'GE Healthcare'] },
  'ON': { name: 'ON Semiconductor', aliases: ['ON Semiconductor', 'onsemi'] },
  'DASH': { name: 'DoorDash', aliases: ['DoorDash'] },
  'IDXX': { name: 'IDEXX', aliases: ['IDEXX Laboratories'] },
  'BIIB': { name: 'Biogen', aliases: ['Biogen'] },
  'CDW': { name: 'CDW', aliases: ['CDW Corporation'] },
  'CSGP': { name: 'CoStar', aliases: ['CoStar Group'] },
  'ANSS': { name: 'Ansys', aliases: ['Ansys', 'ANSYS'] },
  'FAST': { name: 'Fastenal', aliases: ['Fastenal'] },
  'VRSK': { name: 'Verisk', aliases: ['Verisk Analytics'] },
  'GFS': { name: 'GlobalFoundries', aliases: ['GlobalFoundries', 'GF'] },
  'TRI': { name: 'Thomson Reuters', aliases: ['Thomson Reuters', 'Reuters'] },
  'MRNA': { name: 'Moderna', aliases: ['Moderna'] },
  'EXC': { name: 'Exelon', aliases: ['Exelon'] },
  'XEL': { name: 'Xcel Energy', aliases: ['Xcel Energy'] },
  'CEG': { name: 'Constellation Energy', aliases: ['Constellation Energy'] },
  'CTSH': { name: 'Cognizant', aliases: ['Cognizant'] },
  'BKR': { name: 'Baker Hughes', aliases: ['Baker Hughes'] },
  'AZN': { name: 'AstraZeneca', aliases: ['AstraZeneca'] },
  'ZS': { name: 'Zscaler', aliases: ['Zscaler'] },
  'FANG': { name: 'Diamondback', aliases: ['Diamondback Energy'] },
  'DDOG': { name: 'Datadog', aliases: ['Datadog'] },
  'KDP': { name: 'Keurig Dr Pepper', aliases: ['Keurig', 'Dr Pepper'] },
  'CCEP': { name: 'Coca-Cola Europacific', aliases: ['Coca-Cola Europacific'] },
  'KHC': { name: 'Kraft Heinz', aliases: ['Kraft', 'Heinz', 'Kraft Heinz'] },
  'TTWO': { name: 'Take-Two', aliases: ['Take-Two', 'Rockstar Games', 'GTA', '2K Games'] },
  'EA': { name: 'Electronic Arts', aliases: ['EA', 'Electronic Arts', 'EA Sports', 'FIFA', 'Madden'] },
  'WBD': { name: 'Warner Bros Discovery', aliases: ['Warner Bros', 'Discovery', 'HBO', 'Max'] },
  'MDB': { name: 'MongoDB', aliases: ['MongoDB'] },
  'ARM': { name: 'Arm Holdings', aliases: ['ARM', 'Arm Holdings'] },
  'PDD': { name: 'PDD Holdings', aliases: ['PDD', 'Pinduoduo', 'Temu'] },
} as const;

export type TickerSymbol = keyof typeof NASDAQ_100_COMPANIES;

// Sector mapping for correlation analysis
export const SECTOR_MAPPING: Record<TickerSymbol, string> = {
  'AAPL': 'Technology',
  'MSFT': 'Technology', 
  'GOOGL': 'Technology',
  'GOOG': 'Technology',
  'AMZN': 'Consumer Discretionary',
  'NVDA': 'Technology',
  'META': 'Technology',
  'TSLA': 'Consumer Discretionary',
  'AVGO': 'Technology',
  'COST': 'Consumer Staples',
  'LIN': 'Materials',
  'ADBE': 'Technology',
  'CSCO': 'Technology',
  'AMD': 'Technology',
  'NFLX': 'Communication Services',
  'INTC': 'Technology',
  'MU': 'Technology',
  'MSTR': 'Technology',
  'QCOM': 'Technology',
  'TMUS': 'Communication Services',
  'CMCSA': 'Communication Services',
  'HON': 'Industrials',
  'PEP': 'Consumer Staples',
  'AMGN': 'Healthcare',
  'AMAT': 'Technology',
  'TXN': 'Technology',
  'INTU': 'Technology',
  'ISRG': 'Healthcare',
  'BKNG': 'Consumer Discretionary',
  'SBUX': 'Consumer Discretionary',
  'GILD': 'Healthcare',
  'MDLZ': 'Consumer Staples',
  'ADI': 'Technology',
  'VRTX': 'Healthcare',
  'REGN': 'Healthcare',
  'PANW': 'Technology',
  'LRCX': 'Technology',
  'SNPS': 'Technology',
  'CDNS': 'Technology',
  'MELI': 'Consumer Discretionary',
  'KLAC': 'Technology',
  'ASML': 'Technology',
  'CRWD': 'Technology',
  'AXON': 'Industrials',
  'MRVL': 'Technology',
  'FTNT': 'Technology',
  'ADSK': 'Technology',
  'WDAY': 'Technology',
  'NXPI': 'Technology',
  'ORLY': 'Consumer Discretionary',
  'CTAS': 'Industrials',
  'CSX': 'Industrials',
  'MAR': 'Consumer Discretionary',
  'PCAR': 'Industrials',
  'CHTR': 'Communication Services',
  'AEP': 'Utilities',
  'LULU': 'Consumer Discretionary',
  'ROP': 'Industrials',
  'ABNB': 'Consumer Discretionary',
  'PYPL': 'Financials',
  'PLTR': 'Technology',
  'APP': 'Technology',
  'SHOP': 'Technology',
  'MNST': 'Consumer Staples',
  'ROST': 'Consumer Discretionary',
  'CPRT': 'Industrials',
  'MCHP': 'Technology',
  'DXCM': 'Healthcare',
  'PAYX': 'Industrials',
  'ODFL': 'Industrials',
  'TEAM': 'Technology',
  'TTD': 'Technology',
  'GEHC': 'Healthcare',
  'ON': 'Technology',
  'DASH': 'Consumer Discretionary',
  'IDXX': 'Healthcare',
  'BIIB': 'Healthcare',
  'CDW': 'Technology',
  'CSGP': 'Real Estate',
  'ANSS': 'Technology',
  'FAST': 'Industrials',
  'VRSK': 'Industrials',
  'GFS': 'Technology',
  'TRI': 'Industrials',
  'MRNA': 'Healthcare',
  'EXC': 'Utilities',
  'XEL': 'Utilities',
  'CEG': 'Utilities',
  'CTSH': 'Technology',
  'BKR': 'Energy',
  'AZN': 'Healthcare',
  'ZS': 'Technology',
  'FANG': 'Energy',
  'DDOG': 'Technology',
  'KDP': 'Consumer Staples',
  'CCEP': 'Consumer Staples',
  'KHC': 'Consumer Staples',
  'TTWO': 'Communication Services',
  'EA': 'Communication Services',
  'WBD': 'Communication Services',
  'MDB': 'Technology',
  'ARM': 'Technology',
  'PDD': 'Consumer Discretionary',
};

// Industry relationships for indirect impact analysis
export const INDUSTRY_RELATIONSHIPS = {
  'semiconductors': ['NVDA', 'AMD', 'INTC', 'MU', 'QCOM', 'AVGO', 'MRVL', 'ASML', 'AMAT', 'LRCX', 'KLAC', 'TXN', 'ADI', 'MCHP', 'NXPI', 'ON', 'GFS', 'ARM'],
  'cloud_computing': ['MSFT', 'AMZN', 'GOOGL', 'GOOG', 'ADBE', 'WDAY', 'MDB', 'DDOG'],
  'ai_ml': ['NVDA', 'MSFT', 'GOOGL', 'GOOG', 'META', 'AMZN', 'AMD', 'INTC', 'ADBE', 'CRWD', 'PANW', 'PLTR'],
  'streaming': ['NFLX', 'WBD', 'AAPL', 'AMZN', 'GOOGL', 'GOOG'],
  'evs': ['TSLA'],
  'fintech': ['PYPL', 'INTU'],
  'biotech': ['MRNA', 'GILD', 'AMGN', 'REGN', 'VRTX', 'BIIB'],
  'cybersecurity': ['CRWD', 'PANW', 'FTNT', 'ZS', 'AXON'],
  'software': ['MSFT', 'ADBE', 'INTU', 'ADSK', 'WDAY', 'TEAM', 'SNPS', 'CDNS', 'ANSS'],
  'e_commerce': ['AMZN', 'MELI', 'ABNB', 'DASH', 'PDD', 'SHOP'],
  'healthcare_tech': ['ISRG', 'DXCM', 'IDXX', 'GEHC'],
  'gaming': ['TTWO', 'EA'],
  'telecom': ['TMUS', 'CHTR'],
  'beverages': ['PEP', 'MNST', 'KDP', 'SBUX', 'CCEP'],
  'food': ['COST', 'MDLZ', 'KHC'],
  'retail': ['COST', 'ROST', 'SBUX', 'ORLY', 'LULU'],
  'industrial': ['CSX', 'PCAR', 'CTAS', 'ROP', 'HON'],
  'utilities': ['AEP', 'EXC', 'XEL', 'CEG'],
  'materials': ['LIN'],
  'hospitality': ['MAR'],
  'media': ['CMCSA', 'WBD'],
  'data_analytics': ['PLTR', 'TRI', 'MSTR'],
  'mobile_apps': ['APP'],
} as const;
